### PR TITLE
Bruno devel

### PR DESCRIPTION
**Pull request by staubibr**
reviewed data sources
reviewed output folders
fixed minor issue with package visualization
updated tests

I tried to make sure all the folders would be uploaded to github properly, the tests were running on my machine before I committed. If tests fail, it's possible it's due to a missing folder (github doesn't commit empty folders)

### CODE REVIEW

**Review by romancardenas — CHANGES_REQUESTED** [review]
When running `test_convert` in MacOS, the test `test_function_convert_results_missing_viz_fields` raises a segmentation fault in line 124.

I went deeper on the function and the segmentation fault is raised in `convert.c`, line 233. I'll take a look and try to detect where is the issue

**Comment by francoiseblanc** [comment]
@staubibr I am no longer able to run the demos. Even though the "output" folder is empty, I get the "did you remove the output file..." message. Anyone else has tried running the demos?

**Comment by romancardenas** [comment]
The demo works if you have created all the output directories (`output/conversion`, `output/simulation`, and `output/visualization`). If `output` is an empty directory, it fails.

**Comment by romancardenas** [comment]
I pushed a new commit to this branch. Now, output folders are created, so we won't face these issues again. @staubibr , @francoiseblanc , can you review my last commit, pull it, and make sure that everything still works?

**Comment by staubibr** [comment]
All seems to work now. I tested it from a fresh clone of the repo, all output folders were created correctly.

**Review by romancardenas — APPROVED** [review]
It now works on my side

**Review by francoiseblanc — APPROVED** [review]
I did several tests on my side too and everything works as expected. Kudos to Bruno and Román 💪

**Review by AidanFahlman — APPROVED** [review]
Thanks Bruno and Roman for getting this sorted out, it is all working again on my end!

**Pull request merged**
